import type { Metadata } from "next";
import "./globals.css";
import AppLayout from "@/app/AppLayout"; // 👈 import your client layout
import { UserProvider } from "./context/UserContext";

export const metadata: Metadata = {
  title: "Digitsole",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <AppLayout>{children}</AppLayout>
        </UserProvider>
      </body>
    </html>
  );
}
